server:
  port: 8082

spring:
  cloud:
    function:
      definition: processProduct;
    stream:
      bindings:
        processProduct-in-0:
          destination: workshop.topic
          group: delivery.group
        processProduct-out-0:
          destination: delivery.topic

      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
logging:
  level:
    root: error
    'ru.example.sword.delivery': debug